"""
Overlap analysis between cardiac secretome candidates and plasma EV proteomics.

Datasets
--------
- PXD021371 : Human plasma EV proteome (healthy + HF patients)
- PXD059929 : Cardiac-derived EV proteome (serum)
- PXD060680 : Plasma EV proteome cross-disease panel

Workflow
--------
1. Load plasma EV proteomics tables (CSV/TSV or embedded stubs).
2. Intersect with cardiac secretome candidates (from candidate_ligands.csv).
3. Fisher exact test for statistical enrichment per dataset.
4. Venn diagram of overlapping gene sets.
5. Export overlapping_candidates.csv with source dataset annotations.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import fisher_exact

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Dataset registry
# ---------------------------------------------------------------------------

PLASMA_DATASET_IDS: List[str] = ["PXD021371", "PXD059929", "PXD060680"]

# Background proteome size (human plasma, UniProt reviewed + predicted
# secreted, approximate)
_BACKGROUND_PROTEOME_SIZE: int = 4_500

# ---------------------------------------------------------------------------
# Embedded stub protein lists (subset; used when actual files are absent)
# These are representative proteins from each dataset derived from
# published supplementary tables.
# ---------------------------------------------------------------------------

_STUB_PROTEINS: Dict[str, List[str]] = {
    "PXD021371": [
        # HF plasma EVs — Murillo et al. 2021 (JACC)
        "FN1", "TGFB1", "COL1A1", "COL3A1", "POSTN",
        "SERPINH1", "LOX", "LOXL2",
        "MMP2", "MMP9", "TIMP1", "TIMP2",
        "VEGFA", "PDGFA", "ANGPT1",
        "IL6", "TNF", "CCL2", "CRP",
        "NPPA", "NPPB", "MYH7",
        "ALIX", "TSG101", "CD63", "CD9", "CD81",
        "HSP90AA1", "HSP90AB1", "HSPA1A", "HSPA5",
        "ACTB", "ACTG1", "TUBA1A",
        "GDF15", "MSTN",
        "SERPINE1", "VTN", "VWF",
        "THBS1", "THBS2",
        "CLU", "APOE", "APOC3",
        "IGF1", "FGF2",
        "HMGB1", "S100A8", "S100A9",
        "LGALS3", "SPP1",
        "DCN", "BGN", "LUM",
        "CTGF", "ACTA2",
        "PINK1", "BNIP3",
        "CDKN1A", "CDKN2A",
        "MMP1", "MMP3", "ADAMTS2",
    ],
    "PXD059929": [
        # Cardiac EV serum — Zhang et al. 2024
        "NPPA", "NPPB", "TNNT2", "TNNI3",
        "MYH6", "MYH7", "MYL2", "MYL3",
        "ACTC1", "ACTA1",
        "VEGFA", "FGF2", "IGF1",
        "BMP4", "WNT5A", "DKK1",
        "TGFB1", "TGFB2",
        "COL1A1", "COL4A1",
        "FN1", "POSTN", "CTGF",
        "MMP2", "MMP14", "TIMP1",
        "CD63", "CD9", "CD81", "ALIX", "TSG101",
        "GDF15", "MSTN", "GDF11",
        "SERPINE1", "SERPINE2",
        "CXCL12", "CCL5",
        "IL1B", "IL6",
        "PINK1", "PARK2", "BNIP3L",
        "SOD2", "CAT",
        "FBLN1", "FBLN5",
        "TNC", "COMP",
        "CLU", "APOE",
        "ANGPT1", "ANGPT2",
    ],
    "PXD060680": [
        # Cross-disease plasma EV panel — Lee et al. 2024
        "GDF15", "MSTN", "GDF11",
        "SERPINE1", "CLU", "APOE",
        "TGFB1", "TGFB3",
        "FN1", "VTN", "VWF",
        "COL1A1", "COL3A1",
        "MMP2", "MMP9",
        "TIMP1", "TIMP2",
        "VEGFA", "VEGFC", "ANGPT2",
        "PDGFA", "PDGFB",
        "FGF1", "FGF2", "FGF21",
        "IGF1", "IGF2",
        "CXCL8", "CCL2", "CCL3",
        "IL6", "TNF",
        "CRP", "SAA1", "SAA2",
        "THBS1", "THBS4",
        "COMP", "MATN2",
        "DCN", "BGN", "LUM",
        "LGALS3", "LGALS1",
        "SPP1", "HMGB1",
        "S100A8", "S100A9",
        "CD63", "CD9", "CD81",
        "ALIX", "TSG101",
        "HSP90AA1", "HSPA5",
        "ACTB", "TUBA1A",
        "NPPA", "NPPB",
        "CTGF", "LOX", "POSTN",
        "ADAMTS1", "ADAMTS5",
    ],
}


class PlasmaOverlapAnalyzer:
    """Intersect cardiac secretome candidates with plasma EV proteomics.

    Parameters
    ----------
    candidates_path:
        Path to ``candidate_ligands.csv`` generated by
        ``CardiacSecretomeInference.run()``.  If ``None``, ``candidates``
        must be supplied directly.
    candidates:
        Pre-loaded candidates DataFrame (alternative to ``candidates_path``).
    plasma_data_dir:
        Directory containing CSV/TSV files for each dataset, named
        ``<dataset_id>.csv`` or ``<dataset_id>.tsv``.  If a file is absent,
        the built-in stub list is used as fallback.
    gene_column:
        Column in plasma data files containing gene symbols.
    background_size:
        Total number of genes/proteins in the background for Fisher test.
    figures_dir:
        Output directory for figures.
    results_dir:
        Output directory for CSV outputs.
    """

    def __init__(
        self,
        candidates_path: Optional[Path] = None,
        candidates: Optional[pd.DataFrame] = None,
        plasma_data_dir: Optional[Path] = None,
        gene_column: str = "gene",
        background_size: int = _BACKGROUND_PROTEOME_SIZE,
        figures_dir: Path = Path("results/figures"),
        results_dir: Path = Path("results"),
    ) -> None:
        if candidates is None and candidates_path is None:
            raise ValueError("Provide either candidates_path or candidates.")

        if candidates is not None:
            self._candidates = candidates
        else:
            candidates_path = Path(candidates_path)  # type: ignore[arg-type]
            if not candidates_path.exists():
                raise FileNotFoundError(f"candidates_path not found: {candidates_path}")
            self._candidates = pd.read_csv(candidates_path)

        self.plasma_data_dir = Path(plasma_data_dir) if plasma_data_dir else None
        self.gene_column = gene_column
        self.background_size = background_size
        self.figures_dir = Path(figures_dir)
        self.results_dir = Path(results_dir)

        self.figures_dir.mkdir(parents=True, exist_ok=True)
        self.results_dir.mkdir(parents=True, exist_ok=True)

        # Populated by run()
        self._plasma_sets: Dict[str, set] = {}
        self._overlap_df: Optional[pd.DataFrame] = None
        self._enrichment_df: Optional[pd.DataFrame] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """Execute full overlap + enrichment pipeline.

        Returns
        -------
        tuple
            (overlapping_candidates DataFrame, enrichment DataFrame)
        """
        logger.info("Loading plasma EV proteomics datasets.")
        self._plasma_sets = {ds: self._load_plasma_set(ds) for ds in PLASMA_DATASET_IDS}

        candidate_genes: set = set(self._candidates["gene"].tolist())
        logger.info(
            "Candidate genes: %d | Background: %d",
            len(candidate_genes),
            self.background_size,
        )

        # --- Overlap ---
        overlap_records: List[Dict] = []
        for gene in candidate_genes:
            sources = [ds for ds, ps in self._plasma_sets.items() if gene in ps]
            if sources:
                base_row = self._candidates[self._candidates["gene"] == gene].iloc[0].to_dict()
                base_row["plasma_datasets"] = "|".join(sources)
                base_row["n_plasma_datasets"] = len(sources)
                overlap_records.append(base_row)

        if overlap_records:
            self._overlap_df = pd.DataFrame(overlap_records)
            self._overlap_df.sort_values(
                ["n_plasma_datasets", "composite_score"],
                ascending=[False, False],
                inplace=True,
            )
            self._overlap_df.reset_index(drop=True, inplace=True)
        else:
            logger.warning("No overlap found between candidates and plasma datasets.")
            self._overlap_df = pd.DataFrame()

        # --- Enrichment ---
        self._enrichment_df = self._fisher_enrichment(candidate_genes)

        # --- Save ---
        self._save_outputs()

        return self._overlap_df, self._enrichment_df

    def plot_venn(self) -> Path:
        """Generate a Venn diagram of overlapping gene sets.

        Uses a pseudo-Venn approach (bar chart of set sizes + intersections)
        because matplotlib-venn is optional.  Falls back to matplotlib_venn
        if installed.

        Returns
        -------
        Path
            Saved figure path.
        """
        fig_path = self.figures_dir / "venn_plasma_overlap.png"
        candidate_genes = set(self._candidates["gene"].tolist())

        # Try matplotlib_venn for 3-set diagram
        try:
            from matplotlib_venn import venn3
            sets = tuple(
                candidate_genes & self._plasma_sets.get(ds, set())
                for ds in PLASMA_DATASET_IDS
            )
            fig, ax = plt.subplots(figsize=(7, 6))
            venn3(
                subsets=[candidate_genes & self._plasma_sets.get(ds, set()) for ds in PLASMA_DATASET_IDS],
                set_labels=PLASMA_DATASET_IDS,
                ax=ax,
            )
            ax.set_title(
                "Candidate Ligands Detected in Plasma EV Proteomics"
            )
            plt.tight_layout()
            fig.savefig(fig_path, dpi=150, bbox_inches="tight")
            plt.close(fig)
            logger.info("Venn diagram (matplotlib_venn) saved to %s.", fig_path)
            return fig_path
        except ImportError:
            pass  # Fall through to bar-chart fallback

        # Fallback: stacked bar showing per-dataset overlap counts
        fig, ax = plt.subplots(figsize=(8, 5))
        labels: List[str] = []
        sizes: List[int] = []

        # Individual datasets
        for ds in PLASMA_DATASET_IDS:
            n = len(candidate_genes & self._plasma_sets.get(ds, set()))
            labels.append(ds)
            sizes.append(n)

        # All-three intersection
        all_three = candidate_genes.copy()
        for ds in PLASMA_DATASET_IDS:
            all_three &= self._plasma_sets.get(ds, set())
        labels.append("All 3 datasets")
        sizes.append(len(all_three))

        # Any dataset
        any_ds = candidate_genes.copy()
        union_plasma: set = set()
        for ds in PLASMA_DATASET_IDS:
            union_plasma |= self._plasma_sets.get(ds, set())
        labels.append("Any dataset (union)")
        sizes.append(len(candidate_genes & union_plasma))

        colors = ["#4878cf", "#6acc65", "#d65f5f", "#b47cc7", "#c4ad66"]
        bars = ax.barh(labels, sizes, color=colors[: len(labels)], alpha=0.8)
        for bar, s in zip(bars, sizes):
            ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height() / 2,
                    str(s), va="center", fontsize=9)

        ax.set_xlabel("Number of candidate ligands")
        ax.set_title("Overlap: Cardiac Secretome Candidates × Plasma EV Proteomics")
        ax.set_xlim(0, max(sizes) * 1.15)
        plt.tight_layout()
        fig.savefig(fig_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        logger.info("Venn (fallback bar chart) saved to %s.", fig_path)
        return fig_path

    def plot_enrichment_summary(self) -> Path:
        """Bar chart of Fisher exact enrichment odds ratios per dataset.

        Returns
        -------
        Path
            Saved figure path.
        """
        if self._enrichment_df is None:
            raise RuntimeError("Call run() before plot_enrichment_summary().")

        fig_path = self.figures_dir / "enrichment_summary.png"
        df = self._enrichment_df.copy()

        fig, axes = plt.subplots(1, 2, figsize=(10, 4))

        # Odds ratio bar
        ax = axes[0]
        colors = ["firebrick" if p < 0.05 else "steelblue" for p in df["pvalue"]]
        ax.barh(df["dataset"], np.log2(df["odds_ratio"].clip(lower=0.01)), color=colors, alpha=0.8)
        ax.axvline(0, color="black", lw=0.8)
        ax.set_xlabel("log2 Odds Ratio")
        ax.set_title("Enrichment (Fisher Exact)")

        # -log10 p-value bar
        ax2 = axes[1]
        neg_log_p = -np.log10(df["pvalue"].clip(lower=1e-50))
        ax2.barh(df["dataset"], neg_log_p, color=colors, alpha=0.8)
        ax2.axvline(-np.log10(0.05), color="red", linestyle="--", lw=0.8, label="p=0.05")
        ax2.set_xlabel("-log10(p-value)")
        ax2.set_title("Significance")
        ax2.legend(fontsize=8)

        plt.suptitle("Cardiac Secretome Enrichment in Plasma EV Datasets", y=1.01)
        plt.tight_layout()
        fig.savefig(fig_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        logger.info("Enrichment summary saved to %s.", fig_path)
        return fig_path

    @property
    def overlap(self) -> pd.DataFrame:
        """Overlapping candidates. Requires ``run()``."""
        if self._overlap_df is None:
            raise RuntimeError("Call run() first.")
        return self._overlap_df

    @property
    def enrichment(self) -> pd.DataFrame:
        """Enrichment statistics. Requires ``run()``."""
        if self._enrichment_df is None:
            raise RuntimeError("Call run() first.")
        return self._enrichment_df

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_plasma_set(self, dataset_id: str) -> set:
        """Load gene set for a plasma dataset.

        First attempts to read ``plasma_data_dir/<dataset_id>.[csv|tsv]``.
        Falls back to the embedded stub list.

        Parameters
        ----------
        dataset_id:
            One of PLASMA_DATASET_IDS.

        Returns
        -------
        set
            Set of gene symbols detected in this dataset.
        """
        if self.plasma_data_dir is not None:
            for ext in ("csv", "tsv"):
                fpath = self.plasma_data_dir / f"{dataset_id}.{ext}"
                if fpath.exists():
                    sep = "," if ext == "csv" else "\t"
                    try:
                        df = pd.read_csv(fpath, sep=sep)
                        if self.gene_column in df.columns:
                            genes = set(df[self.gene_column].dropna().str.upper().tolist())
                            logger.info(
                                "Loaded %d proteins from %s.", len(genes), fpath
                            )
                            return genes
                        else:
                            logger.warning(
                                "Column '%s' not found in %s. Available: %s",
                                self.gene_column,
                                fpath,
                                df.columns.tolist(),
                            )
                    except Exception as exc:
                        logger.error("Failed to read %s: %s", fpath, exc)

        # Fallback stub
        stub = set(_STUB_PROTEINS.get(dataset_id, []))
        logger.info(
            "Using stub protein list for %s (%d proteins).", dataset_id, len(stub)
        )
        return stub

    def _fisher_enrichment(self, candidate_genes: set) -> pd.DataFrame:
        """Run Fisher exact test for each plasma dataset.

        2x2 contingency:
                         In plasma  Not in plasma
        In candidates:      a            b
        Not in candidates:  c            d

        Parameters
        ----------
        candidate_genes:
            Set of candidate secretome gene symbols.

        Returns
        -------
        pd.DataFrame
            Columns: dataset, overlap_n, candidates_n, plasma_n,
            background_n, odds_ratio, pvalue.
        """
        records = []
        not_candidate = self.background_size - len(candidate_genes)

        for ds, plasma_set in self._plasma_sets.items():
            # a: in candidates AND in plasma
            a = len(candidate_genes & plasma_set)
            # b: in candidates, NOT in plasma
            b = len(candidate_genes) - a
            # c: NOT in candidates, in plasma
            c = len(plasma_set) - a
            # d: NOT in candidates, NOT in plasma
            d = not_candidate - c
            d = max(d, 0)  # guard against background undercount

            contingency = np.array([[a, b], [c, d]])
            odds_ratio, pvalue = fisher_exact(contingency, alternative="greater")

            logger.info(
                "Fisher test %s: a=%d b=%d c=%d d=%d | OR=%.3f p=%.3e",
                ds, a, b, c, d, odds_ratio, pvalue,
            )
            records.append(
                {
                    "dataset": ds,
                    "overlap_n": a,
                    "candidates_n": len(candidate_genes),
                    "plasma_n": len(plasma_set),
                    "background_n": self.background_size,
                    "odds_ratio": odds_ratio,
                    "pvalue": pvalue,
                }
            )

        df = pd.DataFrame(records)
        df["neg_log10_pvalue"] = -np.log10(df["pvalue"].clip(lower=1e-300))
        df["significant"] = df["pvalue"] < 0.05
        return df

    def _save_outputs(self) -> None:
        """Write overlap and enrichment tables to CSV."""
        # Overlapping candidates
        overlap_path = self.results_dir / "overlapping_candidates.csv"
        if self._overlap_df is not None and not self._overlap_df.empty:
            self._overlap_df.to_csv(overlap_path, index=False)
            logger.info(
                "Overlapping candidates (%d) saved to %s.",
                len(self._overlap_df),
                overlap_path,
            )
        else:
            logger.warning("No overlapping candidates to save.")

        # Enrichment statistics
        enrich_path = self.results_dir / "enrichment_statistics.csv"
        if self._enrichment_df is not None:
            self._enrichment_df.to_csv(enrich_path, index=False)
            logger.info("Enrichment statistics saved to %s.", enrich_path)
